# Generated by Django 5.1.6 on 2025-02-19 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="messagemanagement",
            options={
                "ordering": ["subject"],
                "verbose_name": "письмо",
                "verbose_name_plural": "письма",
            },
        ),
    ]
