# Generated by Django 5.1.6 on 2025-02-19 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_management", "0002_alter_messagemanagement_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingclient",
            options={
                "ordering": ["email", "full_name"],
                "permissions": [
                    ("can_unpublish_client", "Can unpublish client"),
                    ("can_delete_client", "Can delete client"),
                    ("view_all_clients", "View all clients"),
                ],
                "verbose_name": "получатель рассылки",
                "verbose_name_plural": "получатели рассылок",
            },
        ),
        migrations.AddField(
            model_name="mailingclient",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "beginning_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время первой отправки"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Дата и время окончания отправки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("started", "Запущена"),
                            ("finished", "Завершена"),
                        ],
                        default="created",
                        max_length=12,
                        verbose_name="Статус публикации",
                    ),
                ),
                (
                    "clients",
                    models.ManyToManyField(
                        to="mailing_management.mailingclient",
                        verbose_name="Получатели ",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing_management.messagemanagement",
                        verbose_name="Сообщение ",
                    ),
                ),
            ],
        ),
    ]
