# Generated by Django 5.1.6 on 2025-02-24 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mailing_management",
            "0004_alter_newsletter_options_mailingclient_owner_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingclient",
            options={
                "ordering": ["email", "full_name"],
                "permissions": [
                    ("can_unpublish_client", "Can unpublish client"),
                    ("can_delete_client", "Can delete client"),
                    ("view_all_clients", "View all clients"),
                    ("can_create_client", "Can create a client"),
                    ("can_edit_client", "Can edit a client"),
                ],
                "verbose_name": "получатель рассылки",
                "verbose_name_plural": "получатели рассылок",
            },
        ),
        migrations.CreateModel(
            name="NewsletterAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время попытки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("successful", "Успешно"), ("failed", "Не успешно")],
                        max_length=12,
                        verbose_name="Статус попытки",
                    ),
                ),
                (
                    "server_response",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ответ почтового сервера"
                    ),
                ),
                (
                    "newsletter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="mailing_management.newsletter",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "попытка рассылки",
                "verbose_name_plural": "попытки рассылок",
                "ordering": ["-attempt_date"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_sent", models.IntegerField(default=0)),
                ("successful_attempts", models.IntegerField(default=0)),
                ("failed_attempts", models.IntegerField(default=0)),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
